#' Load seurat data
#'
#' Load cite-seq data generated by 10X cellranger into Seurat
#'
#' @param path relative or absolute path to the directory that contains another directory whose name correspond to `id` and contains cellranger output (barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz).
#' @param id used as the project name for the Seurat object.
#'
#' @returns A Seurat object.
#' @export
#'
#' @examples
#' \dontrun{
#' load_seurat_data(path = ".", id = "my_project_id")
#' }
load_seurat_data_10X <- function(path = ".", id = NULL) {
  if (!base::dir.exists(path)) {
    stop("The `path` argument is not valid!")
  }
  cell.data <- Seurat::Read10X(data.dir = path, gene.column = 2, unique.features = TRUE)
  cell <- Seurat::CreateSeuratObject(
    counts = cell.data[["Gene Expression"]],
    project = id,
    min.cells = 3
  )
  cell[["percent.mt"]] <- Seurat::PercentageFeatureSet(cell, pattern = "^(MT-|mt-|Mt-)")
  cell[["HTO"]] <- Seurat::CreateAssayObject(counts = cell.data[["Antibody Capture"]])
  return(cell)
}
