utils::globalVariables(c(
  "y", "resolution", "cluster", "resolution_num", "n", "n_cells", "head",
  "prop", "x", "parent_x", "label", "edge_label", "prop_child", "prop_parent",
  "barycenter", "node_id", "from_cluster", "to_cluster", "to_n_cells",
  "from_n_cells"
))

#' Plot resolution tree
#'
#' Build a directed tree representing how clusters split across mul
#'
#' @param obj A `data.frame` with columns representing clusterings, or a `Seurat` object with clustering metadata.
#' @param prefix Optional character value indicating the prefix used to detect clustering columns when `cluster_name` is not provided.
#' @param resolutions Optional character or numeric vector indicating the resolutions to include. Values may be supplied are prefixed using `prefix`.
#' @param clusters_name Optional character vector of explicit clustering. If provided, `prefix` and `resolution` are ignored for column discovery. The default `NA` triggers automatic detection.
#' @param edge_label_min Numeric scalar indicating the minimum proportion required to display an edge label.
#' @param node_label One of `"cluster_n"`, `"n"`, or `"cluster"`.
#' @param proportion One of `"child"`, or `"parent"`. Control how the edge proportions are computed.
#' @param node_size Numeric scalar to control the nodes size.
#' @param palette A character corresponding to a RColorBrewer palette name.
#'
#' @returns A `ggplot` object
#' @details
#' The function requires at least two clustering columns.
#'
#' If `palette` is a single RColorBrewer palette name, the original palette is
#' used whenever possible. If more colors are needed than that palette supports,
#' additional colors are generated by interpolation from the palette's maximum
#' available colors.
#'
#' @examples
#' meta <- data.frame(
#'   clusters_0.2 = c("0", "0", "1", "1", "2", "2"),
#'   clusters_0.4 = c("0", "1", "1", "2", "3", "3"),
#'   clusters_0.6 = c("0", "1", "2", "2", "3", "4")
#' )
#'
#' p <- plot_resolution_tree(meta)
#' p
#' @export
plot_resolution_tree <- function(
  obj,
  prefix = "clusters_",
  resolutions = NULL,
  clusters_name = NA,
  edge_label_min = 0.1,
  node_label = c("cluster_n", "n", "cluster"),
  proportion = c("child", "parent"),
  node_size = 15,
  palette = "Set2"
) {
  node_label <- match.arg(node_label)
  proportion <- match.arg(proportion)
  meta <- NA
  if (inherits(obj, "Seurat")) {
    meta <- obj@meta.data
  } else if (inherits(obj, "data.frame")) {
    meta <- obj
  } else {
    stop("`obj` must be a Seurat object or a dataframe!")
  }


  meta_names <- colnames(meta)

  resolve_cluster_columns <- function(meta_names, prefix, resolutions, clusters_name) {
    if (!(length(clusters_name) == 1 && is.na(clusters_name))) {
      cols <- as.character(clusters_name)

      missing_cols <- setdiff(cols, meta_names)
      if (length(missing_cols) > 0) {
        stop(
          "`clusters_name` contains columns not found in meta.data: ",
          paste(missing_cols, collapse = ", ")
        )
      }

      return(
        tibble::tibble(col = cols) %>%
          dplyr::mutate(
            resolution = ifelse(
              startsWith(col, prefix),
              sub(paste0("^", prefix), "", col),
              col
            ),
            resolution_num = suppressWarnings(as.numeric(resolution))
          )
      )
    }

    prefix_cols <- grep(paste0("^", prefix), meta_names, value = TRUE)

    if (length(prefix_cols) == 0) {
      stop("No columns found in meta.data starting with prefix '", prefix, "'.")
    }

    available <- tibble::tibble(col = prefix_cols) %>%
      dplyr::mutate(
        resolution = sub(paste0("^", prefix), "", col),
        resolution_num = suppressWarnings(as.numeric(resolution))
      ) %>%
      dplyr::arrange(resolution_num, resolution)

    if (is.null(resolutions)) {
      return(available)
    }

    requested <- as.character(resolutions)

    matched_cols <- purrr::map_chr(requested, function(x) {
      if (x %in% available$col) {
        return(x)
      }

      idx_suffix <- which(available$resolution == x)
      if (length(idx_suffix) == 1) {
        return(available$col[idx_suffix])
      }

      prefixed <- paste0(prefix, x)
      if (prefixed %in% available$col) {
        return(prefixed)
      }

      x_num <- suppressWarnings(as.numeric(x))
      if (!is.na(x_num)) {
        idx_num <- which(!is.na(available$resolution_num) & available$resolution_num == x_num)
        if (length(idx_num) == 1) {
          return(available$col[idx_num])
        }
      }

      stop(
        "Could not match resolution '", x,
        "' to a column in meta.data using prefix '", prefix, "'."
      )
    })

    matched_cols <- unique(matched_cols)

    available %>%
      dplyr::filter(col %in% matched_cols) %>%
      dplyr::mutate(col = factor(col, levels = matched_cols)) %>%
      dplyr::arrange(col) %>%
      dplyr::mutate(col = as.character(col))
  }

  res_df <- resolve_cluster_columns(
    meta_names = meta_names,
    prefix = prefix,
    resolutions = resolutions,
    clusters_name = clusters_name
  )

  if (nrow(res_df) < 2) {
    stop("Need at least two clustering columns to build the tree.")
  }

  meta2 <- meta %>%
    dplyr::mutate(.cell_id = seq_len(dplyr::n()))

  long_df <- purrr::map_dfr(seq_len(nrow(res_df)), function(i) {
    tibble::tibble(
      .cell_id = meta2$.cell_id,
      resolution = as.character(res_df$resolution[i]),
      resolution_num = res_df$resolution_num[i],
      cluster = as.character(meta2[[res_df$col[i]]])
    )
  })

  nodes <- long_df %>%
    dplyr::filter(!is.na(cluster)) %>%
    dplyr::mutate(
      node_id = paste0("res_", resolution, "__cluster_", cluster)
    ) %>%
    dplyr::count(resolution, resolution_num, cluster, node_id, name = "n_cells") %>%
    dplyr::distinct(node_id, .keep_all = TRUE)

  if (nrow(nodes) == 0) {
    stop("No valid nodes could be constructed from the selected columns.")
  }

  if (anyDuplicated(nodes$node_id)) {
    dupes <- unique(nodes$node_id[duplicated(nodes$node_id)])
    stop(
      "Duplicate node IDs detected: ",
      paste(utils::head(dupes, 10), collapse = ", ")
    )
  }

  edges <- purrr::map_dfr(seq_len(nrow(res_df) - 1), function(i) {
    from_col <- res_df$col[i]
    to_col <- res_df$col[i + 1]
    from_res <- as.character(res_df$resolution[i])
    to_res <- as.character(res_df$resolution[i + 1])

    tibble::tibble(
      .cell_id = meta2$.cell_id,
      from_cluster = as.character(meta2[[from_col]]),
      to_cluster = as.character(meta2[[to_col]])
    ) %>%
      dplyr::filter(!is.na(from_cluster), !is.na(to_cluster)) %>%
      dplyr::count(from_cluster, to_cluster, name = "n") %>%
      dplyr::mutate(
        from = paste0("res_", from_res, "__cluster_", from_cluster),
        to   = paste0("res_", to_res, "__cluster_", to_cluster)
      )
  })

  if (nrow(edges) == 0) {
    stop("No edges could be constructed from the selected clustering columns.")
  }

  node_sizes <- nodes %>%
    dplyr::select(node_id, n_cells)

  edges <- edges %>%
    dplyr::left_join(node_sizes, by = c("from" = "node_id")) %>%
    dplyr::rename(from_n_cells = n_cells) %>%
    dplyr::left_join(node_sizes, by = c("to" = "node_id")) %>%
    dplyr::rename(to_n_cells = n_cells) %>%
    dplyr::mutate(
      prop_child = n / to_n_cells,
      prop_parent = n / from_n_cells,
      prop = if (proportion == "child") prop_child else prop_parent,
      edge_label = dplyr::case_when(
        is.na(prop) ~ "",
        !is.finite(prop) ~ "",
        prop < edge_label_min ~ "",
        .default = scales::percent(prop, accuracy = 0.01, decimal.mark = ",")
      )
    )

  res_levels <- unique(res_df$resolution)
  n_res <- length(res_levels)
  fill_values <- if (n_res <= 8) {
    RColorBrewer::brewer.pal(n_res, palette)
  } else {
    grDevices::colorRampPalette(
      RColorBrewer::brewer.pal(8, palette)
    )(n_res)
  }
  names(fill_values) <- res_levels

  nodes <- nodes %>%
    dplyr::mutate(
      resolution = factor(resolution, levels = res_levels),
      y = rev(seq_along(res_levels))[match(as.character(resolution), res_levels)],
      x = NA_real_
    )

  cluster_sort_value <- function(x) {
    x_num <- suppressWarnings(as.numeric(x))
    ifelse(is.na(x_num), Inf, x_num)
  }

  first_res <- res_levels[1]
  first_nodes <- nodes %>%
    dplyr::filter(as.character(resolution) == first_res) %>%
    dplyr::arrange(cluster_sort_value(cluster), cluster) %>%
    dplyr::mutate(x = seq_len(dplyr::n()))

  nodes$x[match(first_nodes$node_id, nodes$node_id)] <- first_nodes$x

  if (length(res_levels) > 1) {
    for (i in 2:length(res_levels)) {
      current_res <- res_levels[i]

      parent_positions <- edges %>%
        dplyr::left_join(
          nodes %>% dplyr::select(node_id, parent_x = x),
          by = c("from" = "node_id")
        ) %>%
        dplyr::group_by(to) %>%
        dplyr::summarise(
          barycenter = stats::weighted.mean(parent_x, w = n, na.rm = TRUE),
          .groups = "drop"
        )

      current_nodes <- nodes %>%
        dplyr::filter(as.character(resolution) == current_res) %>%
        dplyr::left_join(parent_positions, by = c("node_id" = "to")) %>%
        dplyr::arrange(
          is.na(barycenter),
          barycenter,
          dplyr::desc(n_cells),
          cluster_sort_value(cluster),
          cluster
        ) %>%
        dplyr::mutate(x = seq_len(dplyr::n()))

      nodes$x[match(current_nodes$node_id, nodes$node_id)] <- current_nodes$x
    }
  }

  nodes <- nodes %>%
    dplyr::group_by(resolution) %>%
    dplyr::mutate(x = x - mean(x, na.rm = TRUE)) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(
      label = dplyr::case_when(
        node_label == "n" ~ scales::comma(n_cells),
        node_label == "cluster" ~ cluster,
        node_label == "cluster_n" ~ paste0(cluster, "\n(", scales::comma(n_cells), ")")
      )
    )

  vertices <- nodes %>%
    dplyr::transmute(
      name = node_id,
      resolution = as.character(resolution),
      resolution_num,
      cluster,
      n_cells,
      x,
      y,
      label
    )

  graph_edges <- edges %>%
    dplyr::transmute(
      from,
      to,
      n,
      prop,
      prop_child,
      prop_parent,
      edge_label
    )

  g <- igraph::graph_from_data_frame(
    d = graph_edges,
    directed = TRUE,
    vertices = vertices
  )

  p <- ggraph::ggraph(g, layout = "manual", x = igraph::V(g)$x, y = igraph::V(g)$y) +
    ggraph::geom_edge_link(
      ggplot2::aes(width = prop, label = edge_label),
      angle_calc = "along",
      label_dodge = ggplot2::unit(2, "mm"),
      end_cap = ggraph::circle(3, "mm"),
      start_cap = ggraph::circle(3, "mm"),
      alpha = 0.5,
      colour = "grey45",
      arrow = ggplot2::arrow(length = ggplot2::unit(2.2, "mm"), type = "closed"),
      show.legend = FALSE
    ) +
    ggraph::geom_node_point(
      ggplot2::aes(fill = resolution),
      size = node_size,
      shape = 21,
      colour = "black",
      stroke = 0.4
    ) +
    ggraph::geom_node_text(
      ggplot2::aes(label = label),
      size = 3,
      lineheight = 0.95
    ) +
    ggraph::scale_edge_width(range = c(0.3, 3.2)) +
    ggplot2::scale_fill_manual(values = fill_values) +
    ggplot2::scale_y_continuous(
      breaks = rev(seq_along(res_levels)),
      labels = res_levels,
      expand = ggplot2::expansion(mult = c(0.08, 0.08))
    ) +
    ggplot2::labs(
      x = NULL,
      y = "Resolution",
      fill = "Resolution"
    ) +
    ggplot2::coord_cartesian(clip = "off") +
    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::theme(
      panel.grid = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      axis.title.x = ggplot2::element_blank(),
      plot.margin = ggplot2::margin(10, 30, 10, 30)
    )

  return(p)
}
